### ISSUE TITLE
Is there a way to change threshold for nucleus segmentation?

### ISSUE THREAD

**Issue by VasylVaskivskyi** [hammerlab/cytokit#36]
I've noticed that Cytokit segmentation performs poorly on some CODEX datasets. Is there a way to change a threshold that tells which nuclei are allowed to pass. Or maybe there are some other parameters that can influence the quality of nucleus segmentation? I could only find some options that influence size of the nuclei masks.

**Comment by eric-czech** [comment]
The two most important factors I saw for that segmentation model are the zoom of the image and whether or not it was deconvolved.  Are your images at 10x or 20x and not something closer to 40x?  If so, are you using the deconvolution preprocessing?

**Comment by VasylVaskivskyi** [comment]
Thank you for a quick reply. The images are 20x, I run deconvolution and drift compensation. Here is a config file that I use.

```yaml
date: '2021-07-26 16:50:13'
environment: {path_formats: keyence_multi_cycle_v01}
name: e3aa11ba0218456e2cc9302f6b1d9d1c
acquisition:
  axial_resolution: 1500.0
  channel_names: [DAPI-01, Blank, Blank, Blank, DAPI-02, CD31, CD8, CD45, DAPI-03,
    CD20, Ki67, CD3e, DAPI-04, Actin, Podoplan, CD68, DAPI-05, PanCK, CD21, CD4, DAPI-06,
    Empty, CD45RO, CD11c, DAPI-07, Empty, E-CAD, CD107a, DAPI-08, Empty, CD44, H3,
    DAPI-09, Blank, Blank, Blank]
  emission_wavelengths: [358, 750, 550, 650]
  lateral_resolution: 377.40384615384613
  magnification: 20
  num_cycles: 9
  num_z_planes: 1
  numerical_aperture: 0.75
  objective_type: air
  per_cycle_channel_names: [CH1, CH2, CH3, CH4]
  region_height: 10
  region_names: [1]
  region_width: 10
  tile_height: 1000
  tile_overlap_x: 200
  tile_overlap_y: 200
  tile_width: 1000
  tiling_mode: grid
analysis:
- aggregate_cytometry_statistics: {mode: best_z_plane}
operator:
- extract:
    channels: [proc_DAPI-02, proc_CD8, proc_CD20,
      proc_Ki67, proc_CD3e, proc_CD21, proc_CD4, proc_CD45RO, proc_CD11c, proc_E-CAD,
      proc_CD107a]
    name: expressions
    z: all
processor:
  args:
    gpus: [0, 1]
    memory_limit: 64G
    run_best_focus: true
    run_crop: false
    run_cytometry: true
    run_deconvolution: true
    run_drift_comp: true
    run_tile_generator: true
  best_focus: {channel: DAPI-02}
  cytometry:
    membrane_channel_name: CD45
    nuclei_channel_name: DAPI-02
    quantification_params: {cell_graph: true, nucleus_intensity: true}
    segmentation_params: {marker_dilation: 3, marker_min_size: 2, memb_gamma: 0.25,
      memb_min_dist: 8, memb_sigma: 5}
    target_shape: [1000, 1000]
  deconvolution: {n_iter: 25, scale_factor: 0.5}
  drift_compensation: {channel: DAPI-02}
  tile_generator: {raw_file_type: keyence_mixed}
```
